server:
  port: 8800
  servlet:
    context-path: /DMIL

spring:
  application:
    name: test
  # 数据库配置
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/test

  #页面配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix:
      classpath: /templates/,/static/   # 访问template下的html文件需要配置模板，映射
    suffix: .html
    cache: false # 开发时关闭缓存,不然没法看到实时页面



# mapper文件配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

